force-app/main/Investigations/Whistleblower_Management/objects/Action_Taken__c/Action_Taken__c.object-meta.xml
<CustomObject>
    <label>Action Taken</label>
    <nameField>
        <label>Action Taken Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions Taken</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/Investigations/Whistleblower_Management/objects/Action_Taken__c/fields/Action_Date__c.field-meta.xml
<CustomField>
    <fullName>Action_Date__c</fullName>
    <description>Date when the action was taken.</description>
    <inlineHelpText>Date when the action was taken.</inlineHelpText>
    <label>Action Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Action_Taken__c/fields/Action_Details__c.field-meta.xml
<CustomField>
    <fullName>Action_Details__c</fullName>
    <description>Description of the actions taken.</description>
    <inlineHelpText>Description of the actions taken.</inlineHelpText>
    <label>Action Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Action_Taken__c/fields/Effectiveness__c.field-meta.xml
<CustomField>
    <fullName>Effectiveness__c</fullName>
    <description>Assessment of the action&apos;s effectiveness.</description>
    <inlineHelpText
  >Assessment of the action&apos;s effectiveness.</inlineHelpText>
    <label>Effectiveness</label>
    <type>TextArea</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Action_Taken__c/fields/Follow_Up_Required__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if further follow-up actions are required.</description>
    <inlineHelpText>Indicates if further follow-up actions are required.</inlineHelpText>
    <label>Follow Up Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Action_Taken__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Links the action to a specific investigation.</description>
    <inlineHelpText
  >Links the action to a specific investigation.</inlineHelpText>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipLabel>Actions Taken</relationshipLabel>
    <relationshipName>Actions_Taken</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Action_Taken__c/fields/Responsible_Party__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User or team responsible for implementing the action.</description>
    <inlineHelpText>User or team responsible for implementing the action.</inlineHelpText>
    <label>Responsible Party</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Actions_Taken</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Action_Taken__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending Investigation</fullName>
                <default>true</default>
                <label>Pending Investigation</label>
            </value>
            <value>
                <fullName>Terminated Employee</fullName>
            </value>
            <value>
                <fullName>Put Employee On Warning</fullName>
            </value>
            <value>
                <fullName>No Action Taken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Action_Taken__c/fields/Whistleblower_Report__c.field-meta.xml
<CustomField>
    <fullName>Whistleblower_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Whistleblower Report</label>
    <referenceTo>Whistleblower_Report__c</referenceTo>
    <relationshipLabel>Actions Taken</relationshipLabel>
    <relationshipName>Actions_Taken</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Investigation__c/Investigation__c.object-meta.xml
<CustomObject>
    <label>Investigation</label>
    <nameField>
        <label>Investigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/Investigations/Whistleblower_Management/objects/Investigation__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when the investigation was concluded.</description>
    <inlineHelpText>Date when the investigation was concluded.</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Investigation__c/fields/Investigation_Details__c.field-meta.xml
<CustomField>
    <fullName>Investigation_Details__c</fullName>
    <description
  >Detailed notes and findings from the investigation.</description>
    <inlineHelpText
  >Detailed notes and findings from the investigation.</inlineHelpText>
    <label>Investigation Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Investigation__c/fields/Investigator__c.field-meta.xml
<CustomField>
    <fullName>Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description
  >The user or team responsible for the investigation.</description>
    <inlineHelpText
  >The user or team responsible for the investigation.</inlineHelpText>
    <label>Investigator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Investigation__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date/time when the investigation started.</description>
    <inlineHelpText>Date/time when the investigation started.</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Investigation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Pending Report Evaluation</fullName>
                <default>true</default>
                <label>Pending Report Evaluation</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Investigation__c/fields/Whistleblower_Report__c.field-meta.xml
<CustomField>
    <fullName>Whistleblower_Report__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Whistleblower Report</label>
    <referenceTo>Whistleblower_Report__c</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Report__c/Whistleblower_Report__c.object-meta.xml
<CustomObject>
    <label>Submission</label>
    <nameField>
        <label>Whistleblower Report Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Report__c/fields/Anonymous__c.field-meta.xml
<CustomField>
    <fullName>Anonymous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the report was made anonymously.</description>
    <inlineHelpText>Indicates if the report was made anonymously.</inlineHelpText>
    <label>Anonymous</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Report__c/fields/Anonymous_Id__c.field-meta.xml
<CustomField>
    <fullName>Anonymous_Id__c</fullName>
    <description>Used as an identifier for anonymous reporters.</description>
    <displayFormat>WB-{0000}</displayFormat>
    <inlineHelpText>Used as an identifier for anonymous reporters.</inlineHelpText>
    <label>Anonymous Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Report__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Type of issue reported.</description>
    <inlineHelpText>Type of issue reported.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ethics</fullName>
            </value>
            <value>
                <fullName>Safety</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Report__c/fields/Report_Details__c.field-meta.xml
<CustomField>
    <fullName>Report_Details__c</fullName>
    <description>Detailed description of the report.</description>
    <inlineHelpText>Detailed description of the report.</inlineHelpText>
    <label>Report Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Report__c/fields/Reported_Date__c.field-meta.xml
<CustomField>
    <fullName>Reported_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Date when the report was made</description>
    <inlineHelpText>Date when the report was made</inlineHelpText>
    <label>Reported Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Report__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>A numerical value indicating the severity or urgency of the report.</description>
    <inlineHelpText>A numerical value indicating the severity or urgency of the report.</inlineHelpText>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Tracks the status</description>
    <inlineHelpText>Tracks the status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Review</fullName>
                <default>true</default>
                <label>Initial Review</label>
            </value>
            <value>
                <fullName>Under Investigation</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Support__c/Whistleblower_Support__c.object-meta.xml
<CustomObject>
    <label>Support</label>
    <nameField>
        <label>Whistleblower Support Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Support__c/fields/Anonymous__c.field-meta.xml
<CustomField>
    <fullName>Anonymous__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Anonymous</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Support__c/fields/Question_Details__c.field-meta.xml
<CustomField>
    <fullName>Question_Details__c</fullName>
    <label>Question Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Support__c/fields/Reporter_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Reporter_First_Name__c</fullName>
    <formula>Reporter__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reporter First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Support__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Support__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/Investigations/Whistleblower_Management/objects/Whistleblower_Support__c/fields/Whistleblower_Report__c.field-meta.xml
<CustomField>
    <fullName>Whistleblower_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Whistleblower Report</label>
    <referenceTo>Whistleblower_Report__c</referenceTo>
    <relationshipLabel>Whistleblowers Support</relationshipLabel>
    <relationshipName>Whistleblowers_Support</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/Investigations/classes/WhistleblowerController.cls
public without sharing class WhistleblowerController {

    @AuraEnabled(cacheable=true)
    public static List<Whistleblower_Report__c> getReportOptions(Id userId) {
        try {
            // Query Whistleblower Report options created by the user
            List<Whistleblower_Report__c> reports = [
                SELECT Name, Anonymous__c, Category__c, CreatedById, LastModifiedById, 
                    OwnerId, Report_Details__c, Status__c, Severity__c
                FROM Whistleblower_Report__c
                WHERE CreatedById = :userId
            ];

            return reports;
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving report options: ' + e.getMessage());
        }
    }


    @AuraEnabled
    public static List<Whistleblower_Support__c> getSupportCases(Id reportId) {
            try {
                System.debug('TRY START');
                List<Whistleblower_Support__c> supportCases = [
                    SELECT Name, Whistleblower_Report__c, Reporter_First_Name__c, Anonymous__c, 
                        Status__c, Question_Details__c, Response__c
                    FROM Whistleblower_Support__c
                    WHERE Whistleblower_Report__c = :reportId
                ];
                System.debug('TRY NO ERROR');

                return supportCases;
            } catch (Exception e) {
                throw new AuraHandledException('Error retrieving related support cases: ' + e.getMessage());
            }
    }

    @AuraEnabled(cacheable=true)
    public static List<Investigation__c> getRelatedInvestigations(String reportId) {
        try {
            // Query related investigations for the selected report
            List<Investigation__c> investigations = [
                SELECT Name, CreatedById, End_Date__c, Investigation_Details__c, 
                    Investigator__c, LastModifiedById, OwnerId, 
                    Start_Date__c, Whistleblower_Report__c
                FROM Investigation__c
                WHERE Whistleblower_Report__c = :reportId
            ];

            return investigations;
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving related investigations: ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Action_Taken__c> getRelatedActions(List<Id> investigationIds) {
        try {
            // Query related actions with a lookup to Investigation
            List<Action_Taken__c> actions = [
                SELECT Name, Action_Date__c, Action_Details__c, CreatedById, 
                    Effectiveness__c, Follow_Up_Required__c, Investigation__c, 
                    LastModifiedById, OwnerId, Responsible_Party__c
                FROM Action_Taken__c
                WHERE Investigation__c IN :investigationIds
            ];
    
            return actions;
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving related actions: ' + e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Whistleblower_Report__c getReportByUniqueIdentifier(String identifier) {
        return [SELECT Id, Name, Anonymous__c, Category__c, CreatedById, LastModifiedById, 
                OwnerId, Report_Details__c, Reported_Date__c, Status__c, Severity__c
            FROM Whistleblower_Report__c
            WHERE Anonymous_Id__c = :identifier
            LIMIT 1];
    }
    
}